Update cray-application image to 0.2.0
Cray-HPE/uan-product-stream pull request #52
Opened 2022-08-25 15:18 UTC by alanm-hpe

## Summary and Scope

Updates to take the latest stable cray-application image 0.2.0
Reformat vars.sh to adapt to new image publishing format
Use new Jenkins credential for publishing

## Issues and Related PRs

* Resolves [CASMUSER-3060](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-3060)

## Testing

  * `rocket`

### Test description:

Verified the new image would boot. Performed the following checks

* No root password by default
* spire-agent started
* /proc/cmdline could not be read by a regular user so the presigned url could not be determined
* DHCP hostname could be set

## Risks and Mitigations

There may be unforeseen changes from lts/csm-1.2 to lts/csm-1.3, however, this feature is a tech preview
and will continue to be worked on. This is an important change to pick up security fixes via vendoring of
node-images and csm-rpms. Future updates will be much easier now that this change has been made.

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-08-25 15:18 UTC, alanm-hpe commented
Waiting on this PR until merge of:
https://github.com/Cray-HPE/application-image-build/pull/1

2022-08-29 15:28 UTC, keopp-hpe requested changes

2022-08-29 15:28 UTC, keopp-hpe commented on docs/portal/developer-portal/advanced/SLES_Image.md
> +1. Create a presigned URL for the rootfs. This is needed for the node to boot in this release, in the future, this will be integrated to BSS and will not need to performed. This URL will be valid for
...will not need to performed. ==> ...will not need to be performed.

2022-08-29 15:28 UTC, keopp-hpe commented on docs/portal/developer-portal/advanced/SLES_Image.md
> +    ncn-m001# UAN_RELEASE=2.5.2
Should this be 2.5.3?

2022-08-31 14:49 UTC, merged