Casmuser 3130
Cray-HPE/uan-product-stream pull request #70
Opened 2022-11-10 00:42 UTC by keopp-hpe

## Summary and Scope

Document update to include a "Known Issues" section in the guides.

First "Known Issue" is the workaround for the kdump configuration.

## Issues and Related PRs

* Resolves [CASMUSER-3130](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-3130)

## Risks and Mitigations

Low risk

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [X] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-11-10 04:20 UTC, darrenn-jackson requested changes
Just a few minor formatting changes, plus a question.

I checked out this branch and successfully built the HTML5 bundles for both guides and published to ITG. The new "Known Issues" section displays just as expected.

2022-11-10 04:20 UTC, darrenn-jackson commented on docs/portal/developer-portal/index.md
>  ## Table of Contents
this is the first time I remember seeing this file. what do we use it for?

2022-11-10 15:30 UTC, keopp-hpe commented on docs/portal/developer-portal/known_issues/KDUMP_Configuration.md
> +There exists a known bug in the `kdump` Ansible role which prevents kdump from working on UAN nodes.  A workaround for this bug exists and is describe below.
Updated.

2022-11-10 15:30 UTC, keopp-hpe commented on docs/portal/developer-portal/known_issues/KDUMP_Configuration.md
> +### Procedure
Updated.

2022-11-10 15:31 UTC, keopp-hpe commented on docs/portal/developer-portal/known_issues/KDUMP_Configuration.md
> +    ```bash
Updated.

2022-11-10 15:31 UTC, keopp-hpe commented on docs/portal/developer-portal/known_issues/KDUMP_Configuration.md
> +    ```bash
Updated.

2022-11-10 15:32 UTC, keopp-hpe commented on docs/portal/developer-portal/uan_admin_guide.ditamap
> +        <topicref href="known_issues/KDUMP_Configuration.md" format="markdown"/>
Agreed.

2022-11-10 15:32 UTC, keopp-hpe commented on docs/portal/developer-portal/index.md
>  ## Table of Contents
This is part of the hugo docs.

2022-11-10 15:36 UTC, darrenn-jackson approved these changes

2022-11-10 15:59 UTC, alanm-hpe commented on docs/portal/developer-portal/known_issues/KDUMP_Configuration.md
> +    ncn-m001# cray cfs sessions describe nersc-uan
I don't think we should have `nersc-uan` here

2022-11-10 16:00 UTC, alanm-hpe commented on docs/portal/developer-portal/known_issues/KDUMP_Configuration.md
> +    The new interfaces will be available when the UAN is rebooted. Replace the `UAN_SESSION_TEMPLATE` value with the BOS session template name for the UANs.
Should this say "interfaces"?

2022-11-10 16:15 UTC, keopp-hpe commented on docs/portal/developer-portal/known_issues/KDUMP_Configuration.md
> +    ncn-m001# cray cfs sessions describe nersc-uan
Oh, good catch!  Thanks!

2022-11-10 16:15 UTC, keopp-hpe commented on docs/portal/developer-portal/Known_Issues.md
> +# Known Issues
It matches others that provide just a header in the ditaweb sections.  Not used by hugo.  Just the ditaweb docs.

2022-11-10 19:46 UTC, alanm-hpe approved these changes

2022-11-15 20:03 UTC, darrenn-jackson approved these changes

2022-11-15 20:55 UTC, merged