CASMUSER-3182: Backport K3s support
Cray-HPE/uan-product-stream pull request #84
Opened 2023-03-21 17:01 UTC by alanm-hpe

2023-03-21 17:45 UTC, darrenn-jackson requested changes
Several simple formatting changes for readability/skimmability. One spelling error and a couple of questions.

2023-03-21 17:45 UTC, darrenn-jackson commented on docs/portal/developer-portal/test-plan/K3s Test Plan.md
> +To execute this test plan, first identify a UAN that has been fully booted and configured with COS. This means the UAN is configured with the CAN or CHN, and is able to authenticate non-root users.
```suggestion
1. Identify a UAN that has been fully booted and configured with COS. 

  The UAN chosen must be configured with the CAN or CHN, and be able to authenticate non-root users.
  
```

2023-03-21 17:45 UTC, darrenn-jackson commented on docs/portal/developer-portal/test-plan/K3s Test Plan.md
> +1. Verify non-root SSH access to the UAN (make sure to use chn or can based on the default route):
```suggestion
1. Verify non-root SSH access to the UAN.  Use `chn` or `can` depending on the default route):
```

2023-03-21 17:45 UTC, darrenn-jackson commented on docs/portal/developer-portal/test-plan/K3s Test Plan.md
> +1. Once a target UAN has been identified to test, checkout the UAN CFS repository from VCS, and create a new branch. In the following example, the currently booted UAN was configured with `integratio
```suggestion
1. Checkout the UAN CFS repository from VCS and create a new branch. 

  In the following example, the currently booted UAN was configured with `integration-2.6.0`, so that was used as the starting point. Use the correct branch for the UAN being tested.
```

2023-03-21 17:45 UTC, darrenn-jackson commented on docs/portal/developer-portal/test-plan/K3s Test Plan.md
> +1. Complete the [MetalLB section](../advanced/Enabling_K3s.md#metallb) of the Enabling K3s guide. Once completed, modify `vars/uan_helm.yml` (IP addresses masked with `x.x.x.x`) and commit the change
```suggestion
1. Complete the [MetalLB section](../advanced/Enabling_K3s.md#metallb) of the Enabling K3s guide. 

1. Modify `vars/uan_helm.yml` (IP addresses masked with `x.x.x.x`) and commit the change.
```

2023-03-21 17:45 UTC, darrenn-jackson commented on docs/portal/developer-portal/test-plan/K3s Test Plan.md
> +1. Complete the [HAProxy section](../advanced/Enabling_K3s.md#haproxy-configuration) of the Enabling K3s guide. The following changes to `vars/uan_helm.yml` would be suitable changes for validation (
```suggestion
1. Complete the [HAProxy section](../advanced/Enabling_K3s.md#haproxy-configuration) of the Enabling K3s guide. Replace `uan01 uan01.can.lemondrop.hpc.amslabs.hpecorp.net:9000` with the DNS of the UAN chosen for this test.

The following changes to `vars/uan_helm.yml` would be suitable changes for validation:
```

2023-03-21 17:45 UTC, darrenn-jackson commented on docs/portal/developer-portal/test-plan/K3s Test Plan.md
> +1. Complete the  [SSHD section](../advanced/Enabling_K3s.md#sshd-configuration) of the Enabling K3s guide. These changes to `vars/uan_sshd.yml` may be used as a valid test of a podman configuration:
```suggestion
1. Complete the  [SSHD section](../advanced/Enabling_K3s.md#sshd-configuration) of the Enabling K3s guide. 

  These changes to `vars/uan_sshd.yml` may be used as a valid test of a podman configuration:
```

2023-03-21 17:45 UTC, darrenn-jackson commented on docs/portal/developer-portal/test-plan/K3s Test Plan.md
> +1. Create and upload a podman container to the CSM registry. The following example uses the default container image from the User Access Service and should be run from an NCN:
```suggestion
1. Create and upload a podman container to the CSM registry. 

The following example uses the default container image from the User Access Service and should be run from an NCN:
```

2023-03-21 17:45 UTC, darrenn-jackson commented on docs/portal/developer-portal/test-plan/K3s Test Plan.md
> +1. The modified CFS configuration should include the following new playbook after the standard UAN `site.yaml` playbook:
```suggestion
The modified CFS configuration should include the following new playbook after the standard UAN `site.yaml` playbook:
```

2023-03-21 17:45 UTC, darrenn-jackson commented on docs/portal/developer-portal/advanced/Enabling_K3s.md
> +## Configuring K3s, MetalLB, HAProxy, and SSHD for use with Podman
Since this is a 2nd level heading just like the Prerequisites, I assume that this is the actual procedure for enabling K3s?

2023-03-21 17:45 UTC, darrenn-jackson commented on docs/portal/developer-portal/advanced/Enabling_K3s.md
> +Each of the sections below describe how the various comonents deployed to K3s and the UANs may be configured to enable users to SSH to rootless podman containers. As there is no one configuration to
"comonents" should be "components"

2023-03-21 17:58 UTC, alanm-hpe commented on docs/portal/developer-portal/uan_admin.ditamap
> +        <topicref href="advanced/Enabling_K3s.md" format="markdown"/>
This is a PR to `uan-product-stream` for `release/uan-2.5` to make sure we have the docs in this release. Separately, I will make the change to `docs-uan` for 2.5.

2023-03-21 18:03 UTC, darrenn-jackson requested changes
one typo to fix

2023-03-21 18:03 UTC, darrenn-jackson commented on docs/portal/developer-portal/advanced/Enabling_K3s.md
> +Each of the sections below describe how the various comonents deployed to K3s and the UANs may be configured to enable users to SSH to rootless podman containers. As there is no one configuration to
```suggestion
Each of the sections below describe how the various components deployed to K3s and the UANs may be configured to enable users to SSH to rootless podman containers. As there is no one configuration to fit any one use case, read and understand each section to modify the configuration as needed. Once each section has been completed, see [Deploy K3s to the UAN](#deploy-k3s-to-the-uan).
```

2023-03-21 18:09 UTC, alanm-hpe commented on docs/portal/developer-portal/advanced/Enabling_K3s.md
> +## Configuring K3s, MetalLB, HAProxy, and SSHD for use with Podman
Yes

2023-03-21 18:16 UTC, darrenn-jackson submitted a review, later dismissed

2023-03-23 18:05 UTC, alanm-hpe commented
UAN install log
```
ncn-m001:/mnt/developer/alanm/uan-2.5.9-7-g32bfb7f # ./install.sh
+ trap notify ERR
++ dirname ./install.sh
+ ROOTDIR=.
++ craysys metadata get system-name
+ SYS_NAME=groot
++ craysys metadata get site-domain
+ SITE_DOMAIN=hpc.amslabs.hpecorp.net
+ API_GW=https://api.nmnlb.groot.hpc.amslabs.hpecorp.net
+ source ./lib/install.sh
++ : https://packages.local
++ : registry.local
++ export NEXUS_URL
++ : .
++ podman_run_flags=(--network host)
++ declare -a podman_run_flags
++ [[ no == \y\e\s ]]
++ requires curl find podman realpath
++ [[ 4 -gt 0 ]]
++ command -v curl
++ shift
++ [[ 3 -gt 0 ]]
++ command -v find
++ shift
++ [[ 2 -gt 0 ]]
++ command -v podman
++ shift
++ [[ 1 -gt 0 ]]
++ command -v realpath
++ shift
++ [[ 0 -gt 0 ]]
++ vendor_images=()
++ declare -a vendor_images
+ source ./vars.sh
++ UAN_PRODUCT_VERSION=2.5.9-7-g32bfb7f
++ UAN_CONFIG_VERSION=1.9.11
++ PRODUCT_CATALOG_UPDATE_VERSION=1.3.1
++ UAN_IMAGE_VERSION=0.1.0
++ UAN_IMAGE_NAME=cray-application-sles15sp3.x86_64-0.1.0
++ UAN_KERNEL_VERSION=5.3.18-150300.59.87-default
+++ realpath .
++ basename /mnt/developer/alanm/uan-2.5.9-7-g32bfb7f
+ : uan-2.5.9-7-g32bfb7f
+ mkdir -p ./build/manifests
+ manifestgen -i ./manifests/uan.yaml -o ./build/manifests/uan.yaml
+ load-install-deps
+ [[ -f ./vendor/cray-nexus-setup.tar ]]
+ [[ -v CRAY_NEXUS_SETUP_IMAGE ]]
++ load-vendor-image ./vendor/cray-nexus-setup.tar
++ set -o pipefail
++ podman load -q -i ./vendor/cray-nexus-setup.tar
++ sed -e 's/^.*: //'
+ CRAY_NEXUS_SETUP_IMAGE=docker.io/library/cray-nexus-setup:uan-2.5.9-7-g32bfb7f
+ vendor_images+=("$CRAY_NEXUS_SETUP_IMAGE")
+ [[ -f ./vendor/skopeo.tar ]]
+ [[ -v SKOPEO_IMAGE ]]
++ load-vendor-image ./vendor/skopeo.tar
++ set -o pipefail
++ podman load -q -i ./vendor/skopeo.tar
++ sed -e 's/^.*: //'
+ SKOPEO_IMAGE=docker.io/library/skopeo:uan-2.5.9-7-g32bfb7f
+ vendor_images+=("$SKOPEO_IMAGE")
+ nexus-setup blobstores ./nexus-blobstores.yaml
+ nexus-setdefault-credential
+ [[ -v NEXUS_PASSWORD ]]
+ nexus-get-credential
+ requires base64 kubectl
+ [[ 2 -gt 0 ]]
+ command -v base64
+ shift
+ [[ 1 -gt 0 ]]
+ command -v kubectl
+ shift
+ [[ 0 -gt 0 ]]
+ [[ 0 -gt 0 ]]
+ set -- -n nexus nexus-admin-credential
+ kubectl get secret -n nexus nexus-admin-credential
++ base64 -d
++ kubectl get secret -n nexus nexus-admin-credential -o 'jsonpath={.data.username}'
+ export NEXUS_USERNAME=admin
+ NEXUS_USERNAME=admin
++ kubectl get secret -n nexus nexus-admin-credential -o 'jsonpath={.data.password}'
++ base64 -d
+ export NEXUS_PASSWORD=EcvveawHHqtQPkAOEapCdRiVDYUrmz5VIr9FE6-vanU=
+ NEXUS_PASSWORD=EcvveawHHqtQPkAOEapCdRiVDYUrmz5VIr9FE6-vanU=
+ return 0
++ realpath ./nexus-blobstores.yaml
+ podman run --rm --network host -v /mnt/developer/alanm/uan-2.5.9-7-g32bfb7f/nexus-blobstores.yaml:/config.yaml:ro -e NEXUS_URL -e NEXUS_USERNAME -e NEXUS_PASSWORD docker.io/library/cray-nexus-setup:uan-2.5.9-7-g32bfb7f nexus-blobstores-create /config.yaml
Creating file blobstore: uan... 400 FAIL
Updating file blobstore: uan... 204 OK updated
+ nexus-setup repositories ./nexus-repositories.yaml
+ nexus-setdefault-credential
+ [[ -v NEXUS_PASSWORD ]]
+ [[ -n EcvveawHHqtQPkAOEapCdRiVDYUrmz5VIr9FE6-vanU= ]]
+ return 0
++ realpath ./nexus-repositories.yaml
+ podman run --rm --network host -v /mnt/developer/alanm/uan-2.5.9-7-g32bfb7f/nexus-repositories.yaml:/config.yaml:ro -e NEXUS_URL -e NEXUS_USERNAME -e NEXUS_PASSWORD docker.io/library/cray-nexus-setup:uan-2.5.9-7-g32bfb7f nexus-repositories-create /config.yaml
Looking for raw/hosted repository: uan-2.5.9-sle-15sp4... Found...Updating raw/hosted repository: uan-2.5.9-sle-15sp4...204 OK updated
Looking for raw/group repository: uan-2.5-sle-15sp4... Found...Updating raw/group repository: uan-2.5-sle-15sp4...204 OK updated
Looking for raw/hosted repository: uan-2.5.9-sle-15sp3... Found...Updating raw/hosted repository: uan-2.5.9-sle-15sp3...204 OK updated
Looking for raw/group repository: uan-2.5-sle-15sp3... Found...Updating raw/group repository: uan-2.5-sle-15sp3...204 OK updated
Looking for raw/hosted repository: uan-2.5.9-third-party... Found...Updating raw/hosted repository: uan-2.5.9-third-party...204 OK updated
Looking for raw/group repository: uan-2.5-third-party... Found...Updating raw/group repository: uan-2.5-third-party...204 OK updated
+ export SKOPEO_IMAGE=docker.io/library/skopeo:uan-2.5.9-7-g32bfb7f
+ SKOPEO_IMAGE=docker.io/library/skopeo:uan-2.5.9-7-g32bfb7f
+ export CRAY_NEXUS_SETUP_IMAGE=docker.io/library/cray-nexus-setup:uan-2.5.9-7-g32bfb7f
+ CRAY_NEXUS_SETUP_IMAGE=docker.io/library/cray-nexus-setup:uan-2.5.9-7-g32bfb7f
+ [[ -f ./lib/nexus-upload.sh ]]
+ . ./lib/nexus-upload.sh
+++ dirname ./lib/nexus-upload.sh
++ ROOTDIR=./lib/..
++ source ./lib/../lib/install.sh
+++ : https://packages.local
+++ : registry.local
+++ export NEXUS_URL
+++ : ./lib/..
+++ podman_run_flags=(--network host)
+++ declare -a podman_run_flags
+++ [[ no == \y\e\s ]]
+++ requires curl find podman realpath
+++ [[ 4 -gt 0 ]]
+++ command -v curl
+++ shift
+++ [[ 3 -gt 0 ]]
+++ command -v find
+++ shift
+++ [[ 2 -gt 0 ]]
+++ command -v podman
+++ shift
+++ [[ 1 -gt 0 ]]
+++ command -v realpath
+++ shift
+++ [[ 0 -gt 0 ]]
+++ vendor_images=()
+++ declare -a vendor_images
++ skopeo-sync ./lib/../docker
++ local src=./lib/../docker
++ [[ -d ./lib/../docker ]]
++ nexus-setdefault-credential
++ [[ -v NEXUS_PASSWORD ]]
++ [[ -n EcvveawHHqtQPkAOEapCdRiVDYUrmz5VIr9FE6-vanU= ]]
++ return 0
+++ realpath ./lib/../docker
++ podman run --rm --network host -v /mnt/developer/alanm/uan-2.5.9-7-g32bfb7f/docker:/image:ro docker.io/library/skopeo:uan-2.5.9-7-g32bfb7f sync --scoped --src dir --dest docker --dest-creds admin:EcvveawHHqtQPkAOEapCdRiVDYUrmz5VIr9FE6-vanU= --dest-tls-verify=false /image registry.local
time="2023-03-22T21:07:36Z" level=info msg="Copying image ref 1/9" from="dir:/image/artifactory.algol60.net/csm-docker/stable/cray-product-catalog-update:1.3.1" to="docker://registry.local/artifactory.algol60.net/csm-docker/stable/cray-product-catalog-update:1.3.1"
Getting image source signatures
Skipping: image already present at destination
time="2023-03-22T21:07:36Z" level=info msg="Copying image ref 2/9" from="dir:/image/artifactory.algol60.net/csm-docker/stable/docker.io/haproxytech/haproxy-alpine:2.6.6" to="docker://registry.local/artifactory.algol60.net/csm-docker/stable/docker.io/haproxytech/haproxy-alpine:2.6.6"
Getting image source signatures
Skipping: image already present at destination
time="2023-03-22T21:07:36Z" level=info msg="Copying image ref 3/9" from="dir:/image/artifactory.algol60.net/csm-docker/stable/docker.io/rancher/local-path-provisioner:v0.0.23" to="docker://registry.local/artifactory.algol60.net/csm-docker/stable/docker.io/rancher/local-path-provisioner:v0.0.23"
Getting image source signatures
Copying blob sha256:213ec9aee27d8be045c6a92b7eac22c9a64b44558193775a1a7f626352392b49
Copying blob sha256:d6dfa94d1f44ba06c355fb5a651ae27dbc0881114f03305e1ea7cc52788b2847
Copying blob sha256:b55e83f10d4df03312f9d081230e190d91d51573ee8cb116a48347925b8a08e4
Copying blob sha256:bec39189e70357237cb6a9295b944b423ee3314cce206ce116709b04c96ceb54
Copying blob sha256:5513eda6c57cbef7402659fc38acefac97689618a516c5f04004f5c6b4c09819
Copying config sha256:ff6a2695e5da67422e107193c07797cfce832b1413a1c44ae8d24c2602321cd8
Writing manifest to image destination
Storing signatures
time="2023-03-22T21:07:37Z" level=info msg="Copying image ref 4/9" from="dir:/image/artifactory.algol60.net/csm-docker/stable/docker.io/rancher/mirrored-coredns-coredns:1.9.4" to="docker://registry.local/artifactory.algol60.net/csm-docker/stable/docker.io/rancher/mirrored-coredns-coredns:1.9.4"
Getting image source signatures
Copying blob sha256:c6824c7a0594e5640ccb153e26696a9f13919ea95bad5c91e43ae298868af828
Copying blob sha256:8f16f0bc6a9b0a6c4f176312d4edb4d2ce9bf05be1321a681f876733a228e9a9
Copying config sha256:9a4fad1223994358079792536f8e66f35cf8dff8fd5bd3b2ece6197297641d09
Writing manifest to image destina [...]

2023-03-23 18:08 UTC, alanm-hpe commented
UAN Bootprep file used to test on groot
```
ncn-m001:/mnt/developer/alanm/bootprep # cat alanm-bootprep.yaml
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
---
configurations:
- name: alanm-uan-config-cos-{{cos.version}}
  layers:
  - name: shs-mellanox_install-integration-{{shs.version}}
    playbook: shs_mellanox_install.yml
    product:
      name: slingshot-host-software
      version: "{{shs.version}}"
      branch: integration-{{shs.version}}
  - name: csm-packages-integration-{{csm.version}}
    playbook: csm_packages.yml
    product:
      name: csm
      version: "{{csm.version}}"
  - name: uan
    playbook: site.yml
    product:
      name: uan
      version: "{{uan.version}}"
      branch: integration-uan-2.5.9-6-ge2e5882
  - name: uan
    playbook: k3s.yml
    product:
      name: uan
      version: "{{uan.version}}"
      branch: integration-uan-2.5.9-6-ge2e5882
  - name: cpe-pe_deploy-integration-{{cpe.version}}
    playbook: pe_deploy.yml
    product:
      name: cpe
      version: "{{cpe.version}}"
      branch: cpe-{{cpe.version.split('.')[0]}}.{{cpe.version.split('.')[1].zfill(2)}}-integration
  - name: analytics-site-integration-{{analytics.version}}
    playbook: site.yml
    product:
      name: analytics
      version: "{{analytics.version}}"
      branch: integration
  - name: slurm-site-{{slurm.version}}
    playbook: site.yml
    product:
      name: slurm
      version: "{{slurm.version}}"
      commit: "53bfbf99074f607336d11b7669f4e39171c5f516"

images:
- name: alanm-uan-kpreslan
  ims:
    is_recipe: false
    #name: kpreslan-20230313190241_cfs_kpreslan-20230313190241
    id: 28c4ab84-7ec1-42eb-a431-7ee0bdbf3060
  configuration: alanm-uan-config-cos-{{cos.version}}
  configuration_group_names:
  - Application
  - Application_UAN

session_templates:
- name: alanm-uan-all-cos-{{cos.version}}
  image: alanm-uan-kpreslan
  configuration: alanm-uan-config-cos-{{cos.version}}
  bos_parameters:
    boot_sets:
      uan:
        kernel_parameters: spire_join_token=${SPIRE_JOIN_TOKEN}
        node_roles_groups:
        - Application
        # If BOS v2 will be used to create the session from this session template,
        # you can target the UAN subrole here instead. E.g.:
        #
        # node_roles_groups:
        # - Application_UAN
        #
        # If not using BOS v2, and the system has other nodes with the
        # "Application" role in HSM that are not UANs, use node_list instead of
        # node_roles_groups. E.g.:
        #
        # node_list:
        # - xname1
        # - xname2
        rootfs_provider_passthrough: "dvs:api-gw-service-nmn.local:300:hsn0,nmn0:0"
```

Product vars tested:
```
ncn-m001:/mnt/developer/alanm/bootprep # cat product_vars.yaml
# Copyright 2022 Hewlett Packard Enterprise Development LP
---
analytics:
  version: 1.3.18
cos:
  version: 2.4.109
cpe:
  version: 22.12.5
csm:
  version: 1.3.1
csm_diags:
  version: 1.3.28
hfp:
  version: 23.01.0
pbs:
  version: 1.2.3
#recipe:
#  version: 22.11.0-alpha.16
sat:
  version: 2.4.13
sdu:
  version: 2.1.3
shs:
  version: 2.0.2-97
sle_sp3:
  version: 22.08.0.20220805
sle_sp4:
  version: 23.02.0.20230216
slingshot:
  version: 2.0.2-941
slurm:
  version: 1.2.8
sma:
  version: 1.7.27
uan:
  version: 2.5.9-7-g32bfb7f
```

Note, a custom image was used due to MQTT DVS testing. It is expected that the image used will be representative of the image built with COS 2.4.111

2023-03-23 21:22 UTC, keopp-hpe approved these changes

2023-03-23 21:23 UTC, merged